"""Workspace initialization and management.

Creates a workspace directory with soul files and a CLAUDE.md that @imports
them. The Claude Agent SDK loads CLAUDE.md (and its @imports) automatically
when ``setting_sources=["project"]`` is set.

Workspace layout::

    workspace/
    ├── CLAUDE.md          # Auto-generated: @imports soul files
    ├── SOUL.md            # Agent personality & boundaries
    ├── IDENTITY.md        # Name, creature type, vibe, emoji
    ├── USER.md            # User profile
    ├── TOOLS.md           # Local tool notes
    ├── AGENTS.md          # Session guidelines & memory rules
    ├── MEMORY.md          # Long-term curated memory
    ├── BOOTSTRAP.md       # First-run onboarding (deleted after setup)
    ├── HEARTBEAT.md       # Periodic check tasks
    ├── .claude/
    │   └── skills/        # SDK-native skills
    │       └── <name>/
    │           └── SKILL.md
    └── memory/            # Daily notes (YYYY-MM-DD.md)
"""

from __future__ import annotations

import shutil
from pathlib import Path

from soul_system.types import ALL_FILENAMES, SOUL_FILENAMES


def get_templates_dir() -> Path:
    """Return the path to the bundled templates directory."""
    return Path(__file__).parent.parent.parent / "templates"


def ensure_workspace(
    workspace_dir: str | Path,
    *,
    seed_templates: bool = True,
) -> Path:
    """Ensure the workspace directory exists and is seeded with templates.

    Creates:
    - Template soul files (SOUL.md, IDENTITY.md, USER.md, etc.)
    - A CLAUDE.md that @imports the soul files
    - ``.claude/skills/`` directory for SDK-native skills
    - ``memory/`` directory for daily notes

    Returns the resolved workspace path.
    """
    workspace = Path(workspace_dir).expanduser().resolve()
    workspace.mkdir(parents=True, exist_ok=True)

    if seed_templates:
        templates_dir = get_templates_dir()
        if templates_dir.is_dir():
            _seed_missing_files(workspace, templates_dir)
        _ensure_claude_md(workspace)

    # Ensure directories exist
    (workspace / ".claude" / "skills").mkdir(parents=True, exist_ok=True)
    (workspace / "memory").mkdir(exist_ok=True)

    return workspace


def _seed_missing_files(workspace: Path, templates_dir: Path) -> None:
    """Copy template files into the workspace for any that are missing."""
    for name in ALL_FILENAMES:
        target = workspace / name
        if target.exists():
            continue

        template = templates_dir / name
        if template.is_file():
            shutil.copy2(template, target)


def _ensure_claude_md(workspace: Path) -> None:
    """Create CLAUDE.md with @import directives if it doesn't exist."""
    claude_md = workspace / "CLAUDE.md"
    if claude_md.exists():
        return

    claude_md.write_text(generate_claude_md(workspace))


def generate_claude_md(workspace: Path) -> str:
    """Generate the CLAUDE.md content with @import for existing soul files.

    Only includes @import for files that actually exist in the workspace.
    """
    lines = [
        "# Soul System",
        "",
        "# This file is auto-generated by soul-system.",
        "# The SDK loads it via setting_sources=[\"project\"] and resolves the @imports.",
        "# Edit the individual soul files directly — not this file.",
        "",
    ]

    for name in SOUL_FILENAMES:
        if (workspace / name).exists():
            lines.append(f"@import {name}")

    # BOOTSTRAP.md is included when present (deleted after onboarding).
    if (workspace / "BOOTSTRAP.md").exists():
        lines.append("")
        lines.append("# First-run onboarding (delete this file after setup)")
        lines.append("@import BOOTSTRAP.md")

    lines.append("")
    return "\n".join(lines)


def refresh_claude_md(workspace_dir: str | Path) -> Path:
    """Regenerate CLAUDE.md to reflect current workspace files.

    Call this after adding/removing soul files to keep @imports in sync.
    Returns the path to the generated CLAUDE.md.
    """
    workspace = Path(workspace_dir).expanduser().resolve()
    claude_md = workspace / "CLAUDE.md"
    claude_md.write_text(generate_claude_md(workspace))
    return claude_md


def is_workspace_bootstrapped(workspace_dir: str | Path) -> bool:
    """Check if the workspace has completed initial onboarding.

    A workspace is considered bootstrapped when BOOTSTRAP.md has been
    deleted (the agent deletes it after the first-run conversation).
    """
    workspace = Path(workspace_dir).expanduser().resolve()
    bootstrap = workspace / "BOOTSTRAP.md"
    identity = workspace / "IDENTITY.md"

    # Onboarding done: BOOTSTRAP.md deleted, IDENTITY.md exists
    if not bootstrap.exists() and identity.exists():
        return True

    return False
